### ISSUE TITLE
[ASK] How you make MakeWASocket () instance accessable for all endpoint

### ISSUE THREAD

**Issue by JunarisAlf** [ookamiiixd/baileys-api#123]
I try to make similar project, but i faced a problem that is i can get access of running instances of MakeWASocket(). In endpoint A i run MakeWAWocket, and in endpoint B i want to sendMassage, and sendMassage is method that belong to MakeWASocket, i try to rerun MakeWASocket in endpoint B with same config, but its crash. 
I see you use session and store, i dont really understand that.
I just want a simple app, with multiFileAuth no need database and other.
How i can access sock variabel which is from MakeWASocket in endpoint B? How i can save/store the sock variabel and get access of it in simple way?
I glad if you can help me

**Comment by ookamiiixd** [comment]
You can see [this](https://github.com/ookamiiixd/baileys-api/blob/862addeead75c53552154e4a1a028a39590732d5/whatsapp.js) for the reference of how to use file based auth state. To access the session instance, simply store it into a top level variable so that you can use it anywhere. Hope this answer your question
