### ISSUE TITLE
How do i add custom auto reply?

### ISSUE THREAD

**Issue by ammar0466** [ookamiiixd/baileys-api#33]
When they typed 'ping' i want to auto reply 'pong'
Thanks

**Comment by ookamiiixd** [comment]
This is an advanced usage for the Baileys library, you should always refer to its docs to learn more. Alright i'll give you some clue to do so.

- Listen to the `message.upsert` event.
- Determine the message. Since message could be anything (text, image, video, etc), you should determine which message are you looking for. For example if it was text message, it will be on `m.messages[0].message.conversation`.
- Compare it. After you got the message, now you can simply compare for it value.
- Send the reply. After you compared it value, now you just need to send another message as the reply.

Here's a simple code example:
```js
wa.ev.on("messages.upsert", async (m) => {
  const msg = m.messages[0]
  const text = msg.message?.conversation ?? null

  if (text === "ping") {
    await wa.sendMessage(msg.key.remoteJid, { text: "pong" })
  }
})
```
