### ISSUE TITLE
Save credential in Database

### ISSUE THREAD

**Issue by manojsitapara** [ookamiiixd/baileys-api#57]
Is there any plan to save session data into database instead of file system?

**Comment by ookamiiixd** [comment]
Well, i've written a simple redis handler before. But the code is really sucks and buggy because it's my first time writing typescript. Also i don't have time to do the tests so i abandoned it.

I'm thinking rewriting a new one when i have free time but it's not gonna anytime soon.

So to answer your question...no, currently there's no plan for such thing.
