### ISSUE TITLE
When send message to new number first time it shows single tick

### ISSUE THREAD

**Issue by aarvee022** [ookamiiixd/baileys-api#69]
When send message to new number first time it shows single tick on our side and Show "Waiting for this message. This may take a while" on receiver side.

Please provide solution at the earliest.

**Comment by ookamiiixd** [comment]
Okay, i'll apply a hotfix asap

**Comment by nogats07** [comment]
After checking, this seems to only happen when the app is outdated. Try updating the whatsapp app then try again.

**Comment by aarvee022** [comment]
i have checked app is updated still has this issue. i have downgraded it to baileys version 4.1.0. the problem is resolved. 
But issue is still there when you use latest version of baileys.

**Comment by aarvee022** [comment]
Any update?

**Comment by ookamiiixd** [comment]
> Any update?

Sorry, i got really busy recently. I'll definitely do it when i have the time.

**Comment by aarvee022** [comment]
any update?

**Comment by ookamiiixd** [comment]
@aarvee022 Chill, please don't bump all the issues since it spammed my notifications. I'm currently working on a custom baileys store and will be focused on this first.

On other hand, i do realize that my codes on this repo is kinda hard to maintain, so i'll probably rewrite things while also solving all the issues.

So please be more patient, i'm definitely giving my best on this.

**Comment by devoioapps** [comment]
I still have error with this, is there any fix ?
