### ISSUE TITLE
Mongo handler

### ISSUE THREAD

**Issue by yuvalwarsh** [ookamiiixd/baileys-api#77]
Are you working on implementing mongo handler, for storing the sessions and chats instead of file system?

Thank you

**Comment by ookamiiixd** [comment]
Well, sort of. I have a plan to make a custom store. I'm gonna use Prisma for that, so that it could support various DBMS supported by Prisma seamlessly.

Keep a note that Prisma requires replication to make it works with MongoDB, please refer [https://www.prisma.io/docs/concepts/database-connectors/mongodb#error-transactions-are-not-supported-by-this-deployment](here).

Also, i will give my best on this, but please don't expect too much.

**Comment by ahmedRSA** [comment]
any update on this?

**Comment by ookamiiixd** [comment]
@ahmedRSA Curerntly working on a small library for this, you can track the progress [here](https://github.com/ookamiiixd/baileys-prisma-store/tree/dev)

**Comment by yuvalwarsh** [comment]
> 



> @ahmedRSA Currently working on a small library for this, you can track the progress [here](https://github.com/ookamiiixd/baileys-prisma-store/tree/dev)

when do you think it will be ready to use?

**Comment by ookamiiixd** [comment]
@yuvalwarsh I couldn't give an estimation but definitely working on this time by time.
